spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/proj2?serverTimezone=Asia/Seoul
    username: user2
    password: 1234
#    servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB  
    
    

    
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  web:
#    resources:
#      static-locations: classpath:/static/,file:./image/
      
        

server:
  port: 8081
  
    
#spring.web.resources.static-locations=classpath:/static/,file:./image/

